version: 2.1

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.1.1
  slack: circleci/slack@4.10.1

jobs:
  build_and_test:
    docker:
      - image: vernaillen/circleci-pnpm:18.7.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: pnpm install
      - run:
          name: Lint
          command: pnpm run lint
      - sonarcloud/scan
      - run:
          name: Build
          command: |
            pnpm run build
            ls dist
      - slack/notify:
          channel: circleci
          event: always

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test:
          context: 
            - SonarCloud
            - Slack